
services:
  db:
    image: postgres
    ports:
      - "5433:5432"  # Mapea el puerto 5432 del contenedor al puerto 5433 de tu máquina
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: TaskManager
    restart: always